---
- name: join centos7 machine to AD

  hosts: "{{ target_group }}"
  become: yes
  become_method: sudo

  vars:
    ad_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62343037343335343032363935653730336133316563613130356532643262393564316132623532
          3262353662326164656463656338643530306434353335350a346165313831663533393336356632
          30643761343532336661653161386636663366386631613632323363313564396566313637626234
          3264363861396462610a636463626366636639363937653739373164333061326465313263346639
          6536
  
  tasks:

  - name: install the latest version of needed packages
    yum:
      name: sssd, realmd, oddjob, oddjob-mkhomedir, adcli, samba-common, samba-common-tools, krb5-workstation, openldap-clients, policycoreutils-python, pexpect
      state: latest

# this check looks broken, but we should see if there is any current realm binding

#  - name: Check if machine is bound
#    shell: /bin/bash -c "realm list | grep sssd"
#    register: realmd_bound
#    changed_when: false
#    ignore_errors: true

# we might also want to check if there is already a computer object for this machine, and 
# skip the join if the machine exists in AD...

# the code below is bad, as it puts the password into the process table. Better would be to write a file
# with that password, then use the arg to realm that allows you to read the password from a file...

  - name: Join system to AD and put the computer object in the Linux OU
    command: /bin/bash -c "echo '{{ ad_password }}' | /usr/sbin/realm join --user=ADMINISTRATOR@radiofreelol.com --computer-ou=OU=linux-machines,DC=radiofreelol,DC=com radiofreelol.com"
#    when: realmd_bound is failed

# need to configure login permissions. This is done with the "realm permit" command, which can take --groups as an arg
# allowing the list of allowed users to be derived from AD group membership

