---
- name: join centos7 machine to AD

  hosts: "{{ target_group }}"
  become: yes
  become_method: sudo

  vars:
    ad_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62343037343335343032363935653730336133316563613130356532643262393564316132623532
          3262353662326164656463656338643530306434353335350a346165313831663533393336356632
          30643761343532336661653161386636663366386631613632323363313564396566313637626234
          3264363861396462610a636463626366636639363937653739373164333061326465313263346639
          6536
  
  tasks:

  - name: debug check that ad_password is set
    debug:
      var: ad_password
  
  - name: install the latest version of sssd
    yum:
      name: sssd
      state: latest

  - name: install the latest version of realmd
    yum:
      name: realmd
      state: latest

  - name: install the latest version of oddjob
    yum:
      name: oddjob
      state: latest

  - name: install the latest version of oddjob-mkhomedir
    yum:
      name: oddjob-mkhomedir
      state: latest

  - name: install the latest version of adcli
    yum:
      name: adcli
      state: latest

  - name: install the latest version of samba-common
    yum:
      name: samba-common
      state: latest

  - name: install the latest version of samba-common-tools
    yum:
      name: samba-common-tools
      state: latest

  - name: install the latest version of krb5-workstation
    yum:
      name: krb5-workstation
      state: latest

  - name: install the latest version of openldap-clients
    yum:
      name: openldap-clients
      state: latest

  - name: install the latest version of policycoreutils-python
    yum:
      name: policycoreutils-python
      state: latest

  - name: install the latest version of pexpect
    yum:
      name: pexpect
      state: latest

# this check looks broken, but we should see if there is any current realm binding

#  - name: Check if machine is bound
#    shell: /bin/bash -c "realm list | grep sssd"
#    register: realmd_bound
#    changed_when: false
#    ignore_errors: true

# we might also want to check if there is already a computer object for this machine, and 
# skip the join if the machine exists in AD...

  - name: Join system to AD and put the computer object in the Linux OU
    command: /bin/bash -c "echo '{{ ad_password }}' | /usr/sbin/realm join --user=ADMINISTRATOR@radiofreelol.com --computer-ou=OU=linux-machines,DC=radiofreelol,DC=com radiofreelol.com"
#    when: realmd_bound is failed
