---
- name: install ceph

  hosts: all
  become: yes
  become_method: sudo

  tasks:

  - name: add epel repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no

  - name: add ceph repository
    yum_repository:
      name: ceph-noarch
      description: ceph noarch packages
      baseurl: https://download.ceph.com/rpm-mimic/el7/noarch
      gpgcheck: no

  - name: install ntp
    yum:
      name: ntp
      state: latest

  - name: install ntpdate
    yum:
      name: ntpdate
      state: latest

  - name: install ntp-doc
    yum:
      name: ntp-doc
      state: latest

  - name: enable ntpd
    service:
      name: ntpd
      enabled: yes
      state: restarted

  - name: push sudoers file
    copy:
      src: /srv/files/ceph/sudoers
      dest: /etc/sudoers.d/ceph-sudoers
      owner: root
      group: root
      mode: 0440

  - name: create sudoers group
    group:
      name: sudoers
      state: present

  - name: create cephdeploy user
    user:
      name: cephdeploy
      groups: sudoers

  - name: create .ssh directory
    file:
      path: /home/cephdeploy/.ssh
      state: directory
      owner: cephdeploy
      group: cephdeploy
      mode: 0755

  - name: push cephdeploy public ssh key
    copy:
      src: /srv/files/ceph/ceph-authorized-keys
      dest: /home/cephdeploy/.ssh/authorized_keys
      owner: cephdeploy
      group: cephdeploy
      mode: 0600

  - name: set selinux permissive
    selinux:
      policy: targeted
      state: permissive
