---
- name: yum install splunk universal forwarder

  hosts: all
  become: yes
  become_method: sudo

  tasks:
  
  - name: Install universal forwarder from RPM from URL
    yum: 
      name: http://north40-rpms.s3-website-us-east-1.amazonaws.com/splunkforwarder-7.2.0-8c86330ac18-linux-2.6-x86_64.rpm 
      state: present
      
  - name: enable forwarder service and accept license
    command: /opt/splunkforwarder/bin/splunk enable boot-start --accept-license --answer-yes --no-prompt

  - name: fetch linux TA
    get_url:
      url: https://s3.amazonaws.com/north40-rpms/splunk-add-on-for-unix-and-linux_600.tgz    
      dest: /tmp
      
  - name: install linux TA
    unarchive:
      src: https://s3.amazonaws.com/north40-rpms/splunk-add-on-for-unix-and-linux_600.tgz
      dest: /opt/splunkforwarder/etc/apps/
      remote_src: yes
    
  - name: set outputs.conf
    copy: 
      src: ./files/splunk-universal-forwarder/outputs.conf
      dest: /opt/splunkforwarder/etc/system/local/outputs.conf
      owner: splunk
      group: splunk
      mode: 0644
  
  - name: create local directory for linux TA
    file:
      path: /opt/splunkforwarder/etc/apps/Splunk_TA_nix/local
      state: directory
      mode: 0755      
    
  - name: set inputs.conf
    copy: 
      src: ./files/splunk-universal-forwarder/inputs.conf
      dest: /opt/splunkforwarder/etc/apps/Splunk_TA_nix/local/inputs.conf
      owner: splunk
      group: splunk
      mode: 0644
    
  - name: start splunk service
    systemd:
      name: splunk
      enabled: yes
      state: restarted
