---
- name: yum update all installed packages

  hosts: all
  become: yes
  become_method: sudo

  tasks:

    - name: yum install latest
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      
    - name: apt cache update
      apt:
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

      - name: apt update latest
      apt:
        name: '*'
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'      
      
    - name: apt autoremove
      apt:
        autoremove: yes
        autoclean: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
