---
- name: yum update all installed packages

  hosts: all
  become: yes
  become_method: sudo

  tasks:

    - name: yum install latest
      command: yum -y update
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      
    - name: apt update
      command: apt update
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'      
