---
- name: run ps against system, verifies connectivity

  hosts: "{{ target_group }}"
  become: yes
  become_method: sudo

  tasks:
  
  - name: run ps process
    command: /bin/ps -faux
    
  - name: post to splunk hec
    uri:
      url: https://splunk.radiofreelol.com:8088/services/collector/event
      force_basic_auth: yes
      user: x
      password: "a67ac3d1-93be-474a-847f-878f00db98b0"
      body: "{'tower-job-id': '{{ tower_job_id }}'}"
      body_format: json
      method: POST
      validate_certs: no
    delegate_to: 127.0.0.1
    
      