---
- name: run ps against system, verifies connectivity

  hosts: "{{ target_group }}"
  become: yes
  become_method: sudo

  tasks:
  
  - name: run ps process
    command: /bin/ps -faux
    
  - name: post to splunk hec
    uri:
      url: http://splunk.radiofreelol.com:8088
      headers:
        Authorization: "Splunk a67ac3d1-93be-474a-847f-878f00db98b0"
      body: "this is a test message from job {{ tower_job_id }}"
    delegate_to: 127.0.0.1
    
      