---
- name: yum install tools packages

  hosts: all
  become: yes
  become_method: sudo

  tasks:

  - name: install net-tools
    yum:
      name: 'net-tools'
      state: latest

  - name: install epel
    yum:
      name: 'epel-release'
      state: latest
      
  - name: install certbot
    yum:
      name: certbot
      state: latest
