---
- name: yum update all installed packages

  hosts: all
  become: yes
  become_method: sudo

  tasks:

  - name: hello
    shell: echo "greetings, program!"
  - name: upgrade all packages
    yum:
      name: '*'
